http://localhost:5001/

### Add a customer
POST http://localhost:5001/addcustomer
Content-Type: application/json

{
  "customer_name": "sai",
  "phone_no": "8096054124",
  "due_amount": 1000,
  "last_updated": "2025-2-8"

}

### Update customer
PUT http://localhost:5001/updatecustomer
Content-Type: application/json

{
  "phone_no": "8096054124",
  "due_amount": 20
}
### remove customer
DELETE http://localhost:5001/removecustomer

{
  "phone_no": "8096054124",
}
